version: '3'
services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306

    volumes:
       - /home/mysql/data:/var/lib/mysql
  spring-boot:
    build: ./
    ports:
      - 8084:8089
    depends_on:
      - database
    restart: on-failure

