version: '2.2'
services:
  applicationAchat:
    build: ../projetAchat
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - mysqldb1
  mysqldb1:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_PASSWORD: wejden
      MYSQL_ROOT_PASSWORD: wejden
      MYSQL_TCP_PORT: 3306
