version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306

  spring-boot:
    image: achat
    container_name: achatproject
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

    restart: on-failure                                                                                                                     ~               