version: '3'
services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wejden
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
    networks:
        - AppNet
    volumes:
       - /home/mysql/data:/var/lib/mysql
  spring-boot:
    image: wejdenmhamdi/projet
    container_name: spring
    ports:
      - 8083:8083
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure