version: '3'
services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: seyf123
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306

    volumes:
       - /home/mysql/data:/var/lib/mysql
  spring-boot:
    build: ./
    container_name: springboot
    ports:
      - 8083:8083
    depends_on:
      - database
    restart: on-failure
