version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wejden
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
    volumes:
       - /home/mysql/data:/var/lib/mysql
  spring-boot:
    image: achat
    container_name: dockercomposeAPP
    ports:
      - 8083:8083
    depends_on:
      - databasee

    restart: on-failure